# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: deploy-dev

on:
  push:
    branches:
      - main

jobs:          
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Install Dependencies
      run: |
          npm install
    - name: sls
      uses: Teakowa/setup-serverless@v2
      with:
        serverless_version: 3.32.2
        provider: aws
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

    - run: |
        ls
        sls deploy
